### PR TITLE
[FIX] *procurement_analytic: duplicated account analytic field in view

### PR DESCRIPTION
**Pull request by cubells**
Twice was added account_analytic_field to the same view.
Update view to merge both changes.
Update README in other modules that depends on procurement analytic.

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You are not changing any view in  sale_procurement_analytic

**Comment by cubells** [comment]
No, I'm not. Views are in procurement_analytic.

**Comment by pedrobaeza** [comment]
Then you shouldn't change the version of that modules. Changing a bit the README doesn't require to change module version number. Any way, I'm wondering why do you remove the "Other information" tab sentence. Are you sure this is not needed? Maybe you have an extra module that shows that information.

**Comment by cubells** [comment]
Because field analytic_account_id is duplicated in form view. It's shown in two locations, in form header and in other information tab. So, with this changes one location disappear. I choose that header location remains in view and remove from other information tab.

**Comment by cubells** [comment]
So README information must be updated in other modules.

**Comment by pedrobaeza** [comment]
This seems a bit strange to not being detected before, but OK if you say so. What I'm also saying is that you don't need to change module version number for only changing the README.

**Comment by cubells** [comment]
@pedrobaeza undo change of versions.

**Review by pedrobaeza — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: I agree with this

**Review by rousseldenis — APPROVED** [review]

**Pull request merged**
