### PR TITLE
[13.0][MIG] analytic_tag_dimension_purchase_warning

### PR DESCRIPTION
**Pull request by i-vyshnevska**
migrate analytic_tag_dimension_purchase_warning
based on https://github.com/OCA/account-analytic/pull/246
build requires merge https://github.com/OCA/account-analytic/pull/264

### CODE REVIEW

**Review by jcoux — APPROVED** [review]

**Review by jcoux — APPROVED** [review]
Code review only.

**Review by TDu — APPROVED** [review]

**Comment by captivea-dcr** [comment]
@i-vyshnevska new based-on PR is #307 
Do you plan to work on this again?

**Comment by i-vyshnevska** [comment]
@captivea-dcr I can give a look after #307 got merged

**Comment by captivea-dcr** [comment]
@i-vyshnevska #310 (replacement of #307)has been merged. Do you plan to work on this one those days?

**Comment by dreispt** [comment]
Lint checks failed

**Comment by rousseldenis** [comment]
@i-vyshnevska analytic_tag_dimension is merged. Could you rebase ?

Could you also respect migrating flow ? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#technical-method-to-migrate-a-module-from-120-to-130-branch

**Pull request closed without merging**
