### PR TITLE
[11.0][MIG] stock_analytic

### PR DESCRIPTION
**Pull request by jaredkipe**
Tests passed with minor changes (11.0 specific needs).
I currently use this in something that makes stock moves on its own, and it works perfectly fine, however...

There is a UX problem in Odoo 11.0 as there is no good way to modify the stock move created on a picking to have an analytic account.  I think I should add that to the current tree view (on the picking) to the left of the 'Initial Demand' field.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's a Travis error

**Review by AaronHForgeFlow — COMMENTED** [review]
IMHO this module should pass also the analytic account from the procurement to the stock move as it is proposed here. https://github.com/OCA/account-analytic/pull/138

**Comment by pedrobaeza** [comment]
On v11 there's no more procurements...

**Comment by AaronHForgeFlow** [comment]
@pedrobaeza yes, sorry, I thought this was 9.0 :face_with_head_bandage:

**Comment by AaronHForgeFlow** [comment]
Commit history is missing thought

**Comment by pedrobaeza** [comment]
Indeed. Thanks for pointing it. @jaredkipe you should preserve commit history following technical method in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Review by AaronHForgeFlow — COMMENTED** [review]
Probably not due this module but the analytic account is not passed from the purchase line to the stock move. As the analytic account cannot be set manually in the stock move, cannot do functional tests. BTW IMHO it'd be great to show the analytic account in the sock move from the picking form view.

**Comment by jaredkipe** [comment]
Closing for branch in #162

**Pull request closed without merging**
