### PR TITLE
[10.0][ADD] mrp_procurement_analytic

### PR DESCRIPTION
**Pull request by rousseldenis**
Depends on :
* [x] https://github.com/OCA/account-analytic/pull/136

### CODE REVIEW

**Comment by rousseldenis** [comment]
@aheficent

**Review by AaronHForgeFlow — COMMENTED** [review]
Nice contribution! It works fine tested on local. 

Only one small thing, is it possible to pass the analytic account also to the manufacturing order?

**Comment by rousseldenis** [comment]
@aheficent I was wondering about that. I see it's a common needs, so let's go!

**Comment by rousseldenis** [comment]
@aheficent Done.
@pedrobaeza Needs review

**Comment by pedrobaeza** [comment]
But the dependency is not yet merged...

**Comment by rousseldenis** [comment]
You can even put your remarks :smiley:

**Comment by pedrobaeza** [comment]
Hehe, indeed, but I have some overload right now.

**Comment by pedrobaeza** [comment]
Please rebase

**Comment by rousseldenis** [comment]
@pedrobaeza Done. v10 tag :smiley:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: The analytic account is also passed to the manufacturing order

**Pull request merged**
