### PR TITLE
[11.0][MIG] pos_analytic_by_config: Migration to 11.0

### PR DESCRIPTION
**Pull request by chienandalu**
Migrated from https://github.com/OCA/account-analytic/pull/95

cc @Tecnativa TT22776 TT24453

### CODE REVIEW

**Comment by Tardo** [comment]
Check Travis

**Comment by chienandalu** [comment]
I think it comes from another module interaction that rewrites the analytic account from the invoice line (my bet goes for product_analytic)

**Comment by chienandalu** [comment]
Changes done to make the module compatible with product_analytic.

**Review by pedrobaeza — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
Tested in production :+1:

**Review by ernestotejeda — APPROVED** [review]

**Pull request closed without merging**
