### PR TITLE
[14.0][MIG] analytic_tag_dimension_enhanced

### PR DESCRIPTION
**Pull request by kittiu**
Standard migration, ready for review.

### CODE REVIEW

**Comment by kittiu** [comment]
ci/runbot is passing. I am not sure why it is not green. But I guess this is ready for review.

```
----------
Module test summary
[1;32mSuccess[0;m account_analytic_parent,analytic_activity_based_cost,analytic_base_department,analytic_tag_dimension,analytic_tag_dimension_enhanced,mrp_analytic

+=======================================
|  Tests summary:
|---------------------------------------
| test_server.py              [1;32mSuccess[0;m
+=======================================
 * Stopping PostgreSQL 9.6 database server       [80G 
[74G[ OK ]
```

**Comment by kittiu** [comment]
cc @ps-tubtim

**Review by Saran440 — APPROVED** [review]
Functional Test :+1: 

WDYT about this PR https://github.com/OCA/account-analytic/pull/387 ?
@kittiu

**Review by ps-tubtim — APPROVED** [review]
Code and Functional Test Ok

**Pull request merged**
