### PR TITLE
[15.0][UPD] Copier update v15

### PR DESCRIPTION
**Pull request by TheerayutEncoder**

### CODE REVIEW

**Comment by TheerayutEncoder** [comment]
@Saran440 Can you help approve this PR?
Thanks

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Thanks @TheerayutEncoder ! this kind of PR can be fast tracked :)

**Comment by TheerayutEncoder** [comment]
OK :+1:

**Pull request merged**
