### PR TITLE
[14.0][REF] account_analytic_wip: simplify dependencies

### PR DESCRIPTION
**Pull request by dreispt**
Depends on:

- [x] https://github.com/OCA/account-analytic/pull/395
- [x] https://github.com/OCA/account-analytic/pull/397

### CODE REVIEW

**Review by patrickrwilson — APPROVED** [review]
LGTM, would be nice to have full test coverage but since this is alpha it looks good to me.

**Comment by dreispt** [comment]
Test coverage was improved :-)

**Comment by dreispt** [comment]
This feels solid now - merging.

**Pull request merged**
