### PR TITLE
[14.0][ADD] pos_stock_analytic

### PR DESCRIPTION
**Pull request by rousseldenis**
Depends on :

- [ ] #382

### CODE REVIEW

**Comment by hitrosol** [comment]
Hi @rousseldenis  do you have plan to put the analytical account in the cost of good sold line (for anglo saxon accounting) in this PR ? Thanks

**Comment by rousseldenis** [comment]
> Hi @rousseldenis do you have plan to put the analytical account in the cost of good sold line (for anglo saxon accounting) in this PR ? Thanks

Not now. But if you want to do a PR on my branch, I can review and merge.

**Comment by hitrosol** [comment]
IMO, my case more relevant in the https://github.com/OCA/account-analytic/tree/14.0/pos_analytic_by_config, than here.
Maybe you can continue to finish this PR since the #382 already merged?

**Comment by rousseldenis** [comment]
> IMO, my case more relevant in the https://github.com/OCA/account-analytic/tree/14.0/pos_analytic_by_config, than here. Maybe you can continue to finish this PR since the #382 already merged?

As I'm not expert in anglo saxon accounting, maybe you can help me improving this ?

**Pull request closed without merging**
