### PR TITLE
[MIG][10.0] migrate pos_analytic_by_config

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**

### CODE REVIEW

**Comment by Cedric-Pigeon** [comment]
@gurneyalex I don't understand why runbot is red. Any idea ?

**Comment by gurneyalex** [comment]
@Cedric-Pigeon if you look at the page https://runbot.odoo-community.org/runbot/repo/github-com-oca-account-analytic-87 you'll see that your branch has the same issue as the target branch. It is in "yellow" meaning that there are some warnings in the logs. 

I submitted #96 on this topic.

**Comment by Cedric-Pigeon** [comment]
@gurneyalex ok, thanks.

**Comment by Cedric-Pigeon** [comment]
@gurneyalex Could you please add the need review label ?

**Comment by Cedric-Pigeon** [comment]
@OCA/pos-maintainers Does anyone can change the IN Progress Label to Needs Review ?

**Comment by pedrobaeza** [comment]
Done

**Comment by Cedric-Pigeon** [comment]
@pedrobaeza thanks

**Comment by feketemihai** [comment]
@Cedric-Pigeon Isn't it easier to use product_analytic module, since you can separate for each product the analytic, not use only one for all products?

**Comment by feketemihai** [comment]
Check also my coments in #55

**Comment by rafaelbn** [comment]
Hi @Cedric-Pigeon 

Do you think this module is better in https://github.com/OCA/pos/ ? I could be better yo hace more visibility for contributors who use POS! :thinking: 

@ovnicraft maybe could you review here? You did duplicate PR :+1:

**Comment by ovnicraft** [comment]
@rafaelbn LGTM and module works tested here; about move to oca/pos +1.

**Comment by ovnicraft** [comment]
what about this ?

**Comment by ovnicraft** [comment]
any new review to merge it?

**Review by moylop260 — APPROVED** [review]
:+1:
Could we merge it since that it is a MIG and new changes could be a new PR?

**Comment by pedrobaeza** [comment]
Please squash together adjacent "OCA Transbot.." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by ovnicraft** [comment]
This is locked 2y, could be merge ?

**Comment by rousseldenis** [comment]
@Cedric-Pigeon

**Review by ovnicraft — APPROVED** [review]

**Comment by moylop260** [comment]
FYI I just squashed together adjacent "OCA Transbot.." commits.

**Comment by ovnicraft** [comment]
@moylop260 something happens, CI crash :(

**Comment by moylop260** [comment]
@ovnicraft 

Yes, maybe there is a compatibility issue or a case not considered since that there is a tests failing:

https://travis-ci.org/OCA/account-analytic/jobs/551536838#L1713
```bash
FAIL
FAIL: test_order_invoice (odoo.addons.pos_analytic_by_config.tests.test_pos_analytic_by_config.TestPosAnalyticConfig)
Traceback (most recent call last):
`   File "/home/travis/build/OCA/account-analytic/pos_analytic_by_config/tests/test_pos_analytic_by_config.py", line 72, in test_order_invoice
`     self.assertEqual(len(lines.ids), 1)
` AssertionError: 0 != 1
FAILED
Module pos_analytic_by_config: 1 failures, 0 errors
```

**Comment by rafaelbn** [comment]
@Cedric-Pigeon , we can merge this if travis is green... :cry:

**Comment by dreispt** [comment]
Travis red. tests are failing. https://travis-ci.org/github/OCA/account-financial-tools/jobs/672493410#L1550

**Pull request closed without merging**
