### PR TITLE
[IMP] account_analytic_distribution: Add analytic tags in distribution

### PR DESCRIPTION
**Pull request by carlosdauden**
@Tecnativa

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please add tests for the new feature

**Comment by carlosdauden** [comment]
Changes done

**Review by pedrobaeza — APPROVED** [review]
Waiting green travis on main branch

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Tested

**Comment by AaronHForgeFlow** [comment]
@pedrobaeza https://github.com/OCA/account-analytic/pull/227 will fix main branch :)

**Comment by pedrobaeza** [comment]
Merging as main branch is now green

**Comment by rousseldenis** [comment]
@pedrobaeza Travis was red. 10.0 branch is red now.

See https://travis-ci.org/OCA/account-analytic/jobs/503077273

@carlosdauden Could you fix it ?

**Comment by carlosdauden** [comment]
@rousseldenis Sorry.
Fixed in https://github.com/OCA/account-analytic/pull/228

**Pull request merged**
