### PR TITLE
[12.0] FIX analytic_tag_dimension when inserting upper case code

### PR DESCRIPTION
**Pull request by eLBati**
otherwise:

tag

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by Saran440 — APPROVED** [review]
Functional Test, LGTM :+1:

**Comment by pedrobaeza** [comment]
@eLBati it seems there's something wrong in the patch. Please rebase over current branch and force push in this PR to see the possible problem.

**Comment by eLBati** [comment]
:thinking: I can't reproduce locally
@angelmoya any hint here?

**Pull request merged**
