### PR TITLE
[14.0][MIG] purchase_analytic

### PR DESCRIPTION
**Pull request by AsierAcedo**

### CODE REVIEW

**Review by urtzi-coninpe — APPROVED** [review]
LGTM

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by AaronHForgeFlow — COMMENTED** [review]
Functional review. Works perfectly.

The only thing is the migration commit. There is no migration commit, just the pre-commit commit. Can you fix that?

**Comment by AaronHForgeFlow** [comment]
Hi @AsierAcedo  those "merge" commits should not be there, it should be just one single commit for the migration. Can you check? Thanks in advance

**Comment by AaronHForgeFlow** [comment]
There are many commits for the migration. Maybe it is best to just retry the migration, you could just save your changes and then git reset --hard origin/14.0 and start the migration as usual: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0 WDYT?

**Comment by rousseldenis** [comment]
@AsierAcedo This is a duplicate of https://github.com/OCA/account-analytic/pull/402

Could you all review that one instead ?

**Comment by rousseldenis** [comment]
@AaronHForgeFlow

**Comment by AaronHForgeFlow** [comment]
I think we should go for the first PR created, that is green BTW

**Pull request closed without merging**
