### PR TITLE
[13.0][MIG] analytic_tag_dimension

### PR DESCRIPTION
**Pull request by Saran440**
reference : https://github.com/OCA/account-analytic/pull/264
- [x] fix bug rename dimension
- [x] test script

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please review #305 and include it here

**Comment by captivea-dcr** [comment]
@pedrobaeza is this one OK?

**Comment by pedrobaeza** [comment]
@captivea-dcr you tell us. Please review it and approve it if you see it correct:

https://odoo-community.org/page/review

**Review by i-vyshnevska — APPROVED** [review]

**Review by captivea-dcr — APPROVED** [review]

**Comment by captivea-dcr** [comment]
@carlosdauden @alexis-via are you ok with this PR? thanks

**Review by carlosdauden — APPROVED** [review]
Rebase from v12 to include the commit that lowercase adds instead of directly modifying it.

**Comment by captivea-dcr** [comment]
@carlosdauden thanks. Maybe i'm wrong but the lowercase is there https://github.com/OCA/account-analytic/pull/307/files#diff-29ac31abb0a13139805e21adc2920646R37 (the same as in v12)

**Comment by pedrobaeza** [comment]
@captivea-dcr but you have copied/pasted instead of cherry-picking the commit, removing the attribution of that change.

**Comment by captivea-dcr** [comment]
oh OK. my bad. I do it now

**Comment by captivea-dcr** [comment]
hum not my branch... isn't this commit https://github.com/OCA/account-analytic/pull/307/commits/f0ac647c7413d865767281fda2d1faba7c74b28c the one with the correct attribution? @eLBati is mentionned so I think @Saran440 cherry-picked the commit, right?

**Comment by carlosdauden** [comment]
Ok I see. It looks like you made cherry-pick.
As the last one appears in the commit history, it seemed to me that it was a manual modification

**Comment by pedrobaeza** [comment]
OK, but I'm missing all the translations. @Saran440 what has happened with them? They aren't administrative commits, but legit translations one, authored by translator.

Selección_010

**Comment by Saran440** [comment]
@pedrobaeza So sorry, I rebase that commit because I think commit created from OCA-Bot
How can I reverse this commit or create new PR?

**Comment by pedrobaeza** [comment]
I have added the note for avoiding confusions in the migration guide (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0), but I'm afraid you have to redo again the commit history for not losing that.

**Comment by Saran440** [comment]
move on https://github.com/OCA/account-analytic/pull/310

**Pull request closed without merging**
