### PR TITLE
[10.0][FIX] purchase_procurement_analytic: Really group by analytic a…

### PR DESCRIPTION
**Pull request by rousseldenis**
…ccount

The search on purchase creation from procurement is done on purchase.order model
Don't use a context change to do so

### CODE REVIEW

**Comment by rousseldenis** [comment]
@Tecnativa

**Comment by pedrobaeza** [comment]
Please check Travis

**Comment by rousseldenis** [comment]
@pedrobaeza See https://github.com/OCA/account-analytic/pull/177

**Comment by pedrobaeza** [comment]
OK, waiting result

**Comment by pedrobaeza** [comment]
You can rebase now

**Comment by rousseldenis** [comment]
@pedrobaeza Done

**Review by pedrobaeza — APPROVED** [review]

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Tested on runbot

**Comment by yajo** [comment]
This can be merged

**Pull request merged**
