### PR TITLE
[10.0][FIX] product_analytic_purchase: Only is executed if exist product

### PR DESCRIPTION
**Pull request by igallart**
If product is empty, _get_product_analytic_accounts from product_analytic module fails

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I don't get why the previous condition is not ok. You are basically making the same check.

**Comment by igallart** [comment]
> I don't get why the previous condition is not ok. You are basically making the same check.

@pedrobaeza, not is the same, when is object new_id created from onchange from another module, it can continue, but is a fake object, and your template is empty and it fails.

**Comment by pedrobaeza** [comment]
No, that can't be, unless you create that product incorrectly in the onchange in a custom module.

**Comment by igallart** [comment]
> No, that can't be, unless you create that product incorrectly in the onchange in a custom module.

It fail when this module is executed first.
https://github.com/OCA/product-variant/blob/10.0/purchase_variant_configurator_on_confirm/models/purchase_order.py#L46

**Comment by pedrobaeza** [comment]
Then you should fix that one instead.

**Comment by igallart** [comment]
Thanks @pedrobaeza, I don't analyze correctly the modules. I will fix in purchase_variant_configurator_on_confirm

**Pull request closed without merging**
