### PR TITLE
[IMP] account_analytic_parent: add tree view to adviser wizard

### PR DESCRIPTION
**Pull request by cubells**
This improve tree view in analytic account wizard for advisers.

The tree view now is like this:

6ed3645e-2b41-11e7-8974-54b3da361d81

cc @Tecnativa @jbeficent

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Don't you remove the other view?

**Comment by cubells** [comment]
@pedrobaeza :

No. The other view is used in Invoicing>Configuration>Analytic accounting>Analytic accounts for maintenance.

**Comment by pedrobaeza** [comment]
I mean the one created under business intelligence menu.

**Comment by cubells** [comment]
Why do you want to remove that view?

**Comment by pedrobaeza** [comment]
Because it's redundant.

**Comment by cubells** [comment]
Then only removing menu is enough. 
We have old tree view in configuration and new tree view for advisers?
Am I right?

**Comment by pedrobaeza** [comment]
Yeah, that's it

**Review by pedrobaeza — APPROVED** [review]
Only one thing more it would be great: create some demo data with the parent accounts and the hierarchy we had on v8

**Comment by pedrobaeza** [comment]
@jbeficent @aheficent please review

**Comment by pedrobaeza** [comment]
I'm remembering another thing: please ensure migration path storing in OpenUpgrade the column and not dropping the view accounts (if not yet done), and here restore them with the appropriate fields.

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: I agree. Better this view in the Chart of analytic accounts than in the Business intelligence menu.

**Pull request merged**
