### PR TITLE
[FIX] [14.0] Create analytic lines if is posted

### PR DESCRIPTION
**Pull request by Shide**
Only create analytic lines if move_id is posted.
Track analytic account and tags fields

@rafaelbn @remi-filament please review

MT-1778 @moduon

### CODE REVIEW

**Review by rafaelbn — APPROVED** [review]
👍

**Review by remi-filament — APPROVED** [review]
Thanks @Shide, makes sense to add another verification here (the only check was on the view where button was shown only for posted entries).
Maybe you can also use parent_state instead of move_id.state ?

**Comment by Shide** [comment]
I've added the tracking fields suggestion https://github.com/OCA/account-analytic/pull/508#pullrequestreview-1218026006

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
