### PR TITLE
[16.0][MIG] product_analytic

### PR DESCRIPTION
**Pull request by chandni299**

### CODE REVIEW

**Review by yweng8111 — APPROVED** [review]

**Comment by antoniocanovas** [comment]
Hello,
It would be good to review README to delete reference to "account_analytic_default". It is not included in v16.

I am reviewing standard and the functionality "analytic distribution model" can do the same as this module + analytic distribution. Perhaps this module will be unused shortly.

**Review by antoniocanovas — APPROVED** [review]
Functional review OK !

**Comment by chandni299** [comment]
> Hello, It would be good to review README to delete reference to "account_analytic_default". It is not included in v16.
> 
> I am reviewing standard and the functionality "analytic distribution model" can do the same as this module + analytic distribution. Perhaps this module will be unused shortly.

Thank you! @antoniocanovas I have made changes as you asked here

**Comment by desdelinux** [comment]
@chandni299 Please, fixing the problem

cc @dreispt

**Comment by rousseldenis** [comment]
@chandni299 I've done a PR to fix the case of void analytic account https://github.com/elego/account-analytic/pull/1

**Comment by CasVissers-360ERP** [comment]
This PR can't be merged without the change of @rousseldenis . Crucial change.

**Comment by desdelinux** [comment]
@chandni299 You can update with the fix of @rousseldenis 

If you want, we do superset

**Comment by desdelinux** [comment]
Replaced here https://github.com/OCA/account-analytic/pull/594

@dreispt @rafaelbn @CasVissers-360ERP @rousseldenis

**Comment by rafaelbn** [comment]
As no answer Replaced by https://github.com/OCA/account-analytic/pull/594

**Pull request closed without merging**
