### PR TITLE
[18.0][MIG] account_analytic_parent: Migration to 18.0

### PR DESCRIPTION
**Pull request by BernatObrador**
Module migrated to version 18.0

cc https://github.com/APSL 161657

@miquelalzanillas @lbarry-apsl @mpascuall @peluko00 @javierobcn @ppyczko please review

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
LGTM, tested in runboat

**Review by ppyczko — APPROVED** [review]
LGTM, tested in runboat

**Review by peluko00 — APPROVED** [review]
LGTM, tested in runboat

**Review by xaviedoanhduy — APPROVED** [review]

**Review by houssine78 — APPROVED** [review]
LGTM

**Comment by houssine78** [comment]
@pedrobaeza this PR seems ready

**Comment by pedrobaeza** [comment]
@houssine78 please stop spamming me. I can't attend all your requests. This has a lot of approvals, but neither from a PSC.

**Comment by houssine78** [comment]
@pedrobaeza ok sorry. I though a PR could be merged once tagged approved and just wanted to speed up the process.

Let's wait for a PSC member to review the PRs then.

**Comment by pedrobaeza** [comment]
Check https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

Most of the times, I launch the merge if the stuff is known or I do a quick review, but you have put me 4 messages in less than a minute about some random PRs, and as said, I can't attend blindly everything, specially if I receive complaints later (check for example https://github.com/OCA/purchase-workflow/pull/2216#issuecomment-2475688663).

**Comment by houssine78** [comment]
Sorry for the inconvenience. I also try to make review even when there is enough ones already done. I'll follow the contribution instruction more carefully as I mostly look at the code.

If there is any way I can help. Let me know.

**Comment by pedrobaeza** [comment]
OK, don't worry. On a quick glance, it seems OK, so let's go with it.

/ocabot merge nobump

**Pull request merged**
