### PR TITLE
[12.0][MIG] account_move_analytic_recreate

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by NuriaXifre** [comment]
I have done a functional review and there is an issue with the analytic lines. The information visualized in the lines does not correspond to a journal item (there is a column of employee, project, duration, task, etc.) I attach a picture of how it looks like:
image

**Comment by MiquelRForgeFlow** [comment]
@NuriaMartinXifre Solved in https://github.com/odoo/odoo/pull/39670.

**Review by NuriaXifre — APPROVED** [review]
Functional review done, the issue with analytic lines view is solved!

**Review by ps-tubtim — APPROVED** [review]
Code LGTM

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
