### PR TITLE
[16.0][ADD] account_analytic_organization: New module account_analytic_organization

### PR DESCRIPTION
**Pull request by mpascuall**
This module adds a new field on the partner. This organization field is also added on the account analytic line and account move line so you can filter and group by it.

cc https://github.com/APSL 160524
@miquelalzanillas @lbarry-apsl @javierobcn @peluko00 @BernatObrador @ppyczko please review

### CODE REVIEW

**Review by peluko00 — APPROVED** [review]
Good work, tested in runboat and code review. LGTM!

**Comment by miquelalzanillas** [comment]
A filter for 'analytic_org_id' field in both search views of journal and analytic entries would be great. Please, can you add it?

image

**Comment by mpascuall** [comment]
> A filter for 'analytic_org_id' field in both search views of journal and analytic entries would be great. Please, can you add it?
> 
> image

Thanks for your feedback! I added the filter in both views

**Comment by miquelalzanillas** [comment]
Hello again @mpascuall ,

I missed to check the form view for the new model 'account.analytic.organization' in the previous review. 

As this new model has a single field ('name') I think would be much useful using inline edition in the list view instead of using the form view.  What do you think?

**Comment by mpascuall** [comment]
> Hello again @mpascuall ,
> 
> I missed to check the form view for the new model 'account.analytic.organization' in the previous review.
> 
> As this new model has a single field ('name') I think would be much useful using inline edition in the list view instead of using the form view. What do you think?

Hi! You're absolutely right, thanks for the feedback! Could you please review again?

**Review by miquelalzanillas — APPROVED** [review]
Code and functional review. LGTM.

**Comment by miquelalzanillas** [comment]
Hi @pedrobaeza ,

Could you review please?

**Review by ppyczko — APPROVED** [review]
LGTM, tested in runboat

**Pull request merged**
