### PR TITLE
[ADD][9.0] sale_analytic_distribution module

### PR DESCRIPTION
**Pull request by cubells**
New module to use as alternative to old sale_analytic_plans module.

- Update README
- Update views
- Update file structure

Depends on
- [x] #90 

cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please rebase now that the dependent module is merged.

**Comment by cubells** [comment]
@pedrobaeza done!

**Review by pedrobaeza — APPROVED** [review]
@luismontalba please review

**Comment by luismontalba** [comment]
I'm not sure about the correct functionality:

1) I create an analytic distribution:

ad

2) I create and confirm a sale order with the analytic distribution selected in the order line:

so

3) I create and confirm invoice from de sale order:

i

4) I can't see any analytic entries created:

ae

**Comment by pedrobaeza** [comment]
This module only transfers analytic distribution from sales order to invoice. When you confirm the invoice is when you get analytic entries, but that's something involved with the already merged module _account_analytic_distribution_.

**Review by luismontalba — APPROVED** [review]
Propagating analytic distribution from sale order to invoice tested on runbot

**Pull request merged**
