### PR TITLE
6.1 fix decimal_precision imports

### LINKED ISSUE #11: 6.1: crash in analytic_multicurrency tests
Error log:

```
2014-09-08 08:19:34,315 23333 CRITICAL openerp_test openerp.modules.module: Couldn't load module analytic_multicurrency
2014-09-08 08:19:34,315 23333 CRITICAL openerp_test openerp.modules.module: 'module' object has no attribute 'decimal_precision'
2014-09-08 08:19:34,316 23333 ERROR openerp_test openerp: Failed to initialize database `openerp_test`.
Traceback (most recent call last):
  File "/home/travis/odoo-6.1/openerp-server", line 95, in preload_registry
    db, registry = openerp.pooler.get_db_and_pool(dbname, update_module=config['init'] or config['update'], pooljobs=False)
  File "/home/travis/odoo-6.1/openerp/pooler.py", line 33, in get_db_and_pool
    registry = RegistryManager.get(db_name, force_demo, status, update_module, pooljobs)
  File "/home/travis/odoo-6.1/openerp/modules/registry.py", line 180, in get
    update_module, pooljobs)
  File "/home/travis/odoo-6.1/openerp/modules/registry.py", line 202, in new
    openerp.modules.load_modules(registry.db, force_demo, status, update_module)
  File "/home/travis/odoo-6.1/openerp/modules/loading.py", line 338, in load_modules
    processed = load_marked_modules(cr, graph, states_to_load, force, status, report, loaded_modules)
  File "/home/travis/odoo-6.1/openerp/modules/loading.py", line 253, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules)
  File "/home/travis/odoo-6.1/openerp/modules/loading.py", line 165, in load_module_graph
    load_openerp_module(package.name)
  File "/home/travis/odoo-6.1/openerp/modules/module.py", line 409, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/home/travis/odoo-6.1/openerp/modules/module.py", line 139, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/home/travis/build/OCA/account-analytic/analytic_multicurrency/__init__.py", line 29, in <module>
    import account_analytic_line
  File "/home/travis/build/OCA/account-analytic/analytic_multicurrency/account_analytic_line.py", line 38, in <module>
    import openerp.addons.decimal_precision as dp
AttributeError: 'module' object has no attribute 'decimal_precision'
```

### PR DESCRIPTION
**Pull request by gurneyalex**
in analytic_multicurrency (closes #11)

removed the trailing whitespace on the edited files

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It still says that there is an error.

Doesn't it be?: `from openerp.addons.decimal_precision import decimal_precision as dp`

**Comment by gurneyalex** [comment]
@pedrobaeza you're right. I fixed this. Travis is now red only because of Flake8 issues.

**Comment by pedrobaeza** [comment]
Thanks :+1:

**Comment by sbidoul** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
