### PR TITLE
[14.0] account_analytic_wip

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by CasVissers-360ERP** [comment]
Interesting modules, are they ready for testing?

**Comment by dreispt** [comment]
@CasVissers-360ERP
Yes it is. This is being used to support an Engineer to order use case.
The tip of the pyramid is at https://github.com/OCA/manufacture/pull/608
You may want to check that one.

**Comment by dreispt** [comment]
@Chandresh-SerpentCS @patrickrwilson Please review

**Comment by patrickrwilson** [comment]
@dreispt Can you fix the test error on Travis:
2021-05-24 13:36:05,812 6014 ERROR openerp_test odoo.addons.account_analytic_wip.tests.test_analytic: ERROR: TestAnalytic.test_100_categ_config_complete
Traceback (most recent call last):
File "/home/travis/build/OCA/account-analytic/setup/account_analytic_wip/odoo/addons/account_analytic_wip/tests/test_analytic.py", line 35, in setUp
"property_cost_variance_account_id": self.variance_account.id,
File "<decorator-gen-65>", line 2, in create
File "/home/travis/OCB-14.0/odoo/api.py", line 344, in _model_create_multi
return create(self, [arg])
File "/home/travis/OCB-14.0/odoo/addons/base/models/ir_fields.py", line 533, in create
recs = super().create(vals_list)
File "<decorator-gen-13>", line 2, in create
File "/home/travis/OCB-14.0/odoo/api.py", line 345, in _model_create_multi
return create(self, arg)
File "/home/travis/OCB-14.0/odoo/models.py", line 3825, in create
raise ValueError("Invalid field %r on model %r" % (key, self._name))
ValueError: Invalid field 'property_cost_wip_journal_id' on model 'product.category'

**Comment by dreispt** [comment]
Superseded by #390

**Pull request closed without merging**
