### PR TITLE
[14][MIG] pos analytic by config xbo

### PR DESCRIPTION
**Pull request by xavier-bouquiaux**

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by rousseldenis** [comment]
@xavier-bouquiaux Could you rebase ?

**Comment by rousseldenis** [comment]
@OCA/pos-maintainers @OCA/accounting-maintainers

**Review by chienandalu — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]

**Review by joao-p-marques — APPROVED** [review]

**Comment by chienandalu** [comment]
Ops. I thought we were on OCA/pos :sweat_smile:

**Comment by hitrosol** [comment]
I try this in my local, the analytical account is recorded in Sales Account, but not in the Cost of Good Sold Account. There is a case where the user would like to know the Income statement based on each Analytical Account, by comparing the Sales vs COGS account. 

image

**Comment by chienandalu** [comment]
> There is a case where the user would like to know the Income statement based on each Analytical Account, by comparing the Sales vs COGS account.

@hitrosol I don't think that's supported. Open an issue or extend via PR once this migration is merged

**Comment by chienandalu** [comment]
@pedrobaeza can you merge here?

**Comment by chienandalu** [comment]
Added the patch catched in this migration to #421

**Pull request merged**
