### PR TITLE
[13.0][MIG] account_analytic_sequence

### PR DESCRIPTION
**Pull request by ps-tubtim**
Standard migration.

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
Please take into account possible merging of https://github.com/OCA/account-analytic/pull/297

**Comment by ps-tubtim** [comment]
@alexey-pelykh I merged https://github.com/OCA/account-analytic/pull/297 to this PR.

**Review by petrus-v — APPROVED** [review]
LGTM thanks

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]

**Comment by HaraldPanten** [comment]
@ps-tubtim could you rebase? I'm not sure about the issue with Travis before merging.

THX

**Comment by ps-tubtim** [comment]
@HaraldPanten I rebased but it seems that this module has a problem with `account_analytic_parent`. Could you suggest a way to resolve this problem for me?

**Comment by petrus-v** [comment]
I had the same problem on https://github.com/OCA/account-analytic/pull/383 porting to v14

I've recently read the following thread which should help to never test those modules together:
https://odoo-community.org/groups/contributors-15/contributors-201141?mode=date&date_begin=2021-07-01&date_end=2021-08-01

but haven't take time to manage it yet !

**Comment by ps-tubtim** [comment]
@petrus-v Thank you for your suggestion.

**Pull request merged**
