### PR TITLE
[13.0][account_analytic_required] company_dependent analytic_policy

### PR DESCRIPTION
**Pull request by ivantodorovich**
Forward-port https://github.com/OCA/account-analytic/pull/292 to 13.0

### CODE REVIEW

**Review by alan196 — APPROVED** [review]
Technical Review 👍

**Comment by ivantodorovich** [comment]
Thank for your review @alan196 !

Would you mind reviewing the `12.0` PR aswell?
https://github.com/OCA/account-analytic/pull/292

**Review by mamcode — APPROVED** [review]
LGTM

**Comment by ivantodorovich** [comment]
ping @OCA/accounting-maintainers

**Comment by ivantodorovich** [comment]
Hi @yvaucher ! This is the `13.0` port of https://github.com/OCA/account-analytic/pull/292
Since that one has been merged, it may be good to merge this one too :)

**Pull request merged**
