### PR TITLE
[13.0][IMP] purchase_analytic: avoid overwrite context in views inherited

### PR DESCRIPTION
**Pull request by ThiagoMForgeFlow**
Change the method of writing the context in the field order_line to avoid overwriting.

@ForgeFlow

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Just for curiosity, what is the other module that needs to put a context there? Is that the purchase standard app?

**Comment by ThiagoMForgeFlow** [comment]
> Just for curiosity, what is the other module that needs to put a context there? Is that the purchase standard app?

I have found the case with the purchase_blanket_order module from purchase-workflow repository

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

This is probably a major change as it adds a new dependency.

**Comment by AaronHForgeFlow** [comment]
Merging to prevent conflicts between oca modules

/ocabot merge major

**Comment by AaronHForgeFlow** [comment]
I just realized that the purchase_blanket_order is overwriting the context same way as this one was doing. I think that module should be fixed as well to inherit from base_view_inheritance_extension. Is that correct?

**Comment by ThiagoMForgeFlow** [comment]
> I just realized that the purchase_blanket_order is overwriting the context same way as this one was doing. I think that module should be fixed as well to inherit from base_view_inheritance_extension. Is that correct?

Correct, the PR is still open: https://github.com/OCA/purchase-workflow/pull/2031

**Pull request merged**
