### PR TITLE
13.0 mig stock analytic

### PR DESCRIPTION
**Pull request by jimhoefnagels**

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Thanks for this!  Could you check if this is applicable also in v13? https://github.com/OCA/account-analytic/pull/288

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:  Functional test on runbot :tada:

**Comment by rven** [comment]
This one should also be applied https://github.com/OCA/account-analytic/pull/286
This PR superseeds https://github.com/OCA/account-analytic/pull/285

**Review by CasVissers-360ERP — APPROVED** [review]
Functional test

**Pull request merged**
