### PR TITLE
[14.0][IMP] mrp_analytic: set MO Analytic on journal items

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by patrickrwilson** [comment]
Code looks good but can't see the logs for why the runbot is failing :(.

**Comment by dreispt** [comment]
@patrickrwilson 
TravisCI runs the tests and checks, you can ignore runbot builds.
So this should  be good to merge once approved.

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Pull request merged**
