### PR TITLE
[17.0] [ADD] account_analytic_spread_by_tag: New module

### PR DESCRIPTION
**Pull request by miquelalzanillas**
This module distributes the amount of the accounting entry among all the analytical accounts that share the same analytical tag. This module is particularly useful for managing costs in projects, departments, or any other analytic dimensions.

Configuration
=============
Before using the module, you need to configure the Analytic Tags and Analytic Accounts.

**Analytic Tags** 

Go to _Accounting > Configuration > Analytic Accounting > Analytic Tags_. 

Create a new tag and enable 'Spread analytic amounts'. Include or exclude analytic accounts while spreading setting the filter located in the same view.

image

**Analytic Accounts** 

Go to _Accounting > Configuration > Analytic Accounting > Analytic Accounts_. 

Create new accounts as needed and set tags mapping field.

image

Usage
=====

While creating an invoice or a move line, you can assign Analytic Tags to each invoice line. These tags will be used to distribute the cost of the line across the associated analytic accounts.

1. Go to _Accounting > Customers > Invoices_. 

2. Click on "_Create_" to create a new invoice. In the invoice lines, select the product, enter the
quantity and price, and select the analytic tags. 

3. After posting invoice or account move, this module will automatically
create analytic lines for each invoice line based on the associated analytic tags.

Click on "_Post_" to post the invoice. Go to _Accounting > Analytic
Accounting > Analytic Items_ to see the created analytic lines.

image

3. **Cancelling invoice or move**: If you cancel the invoice or move, associated analytic lines will be
   automatically deleted.

@peluko00 @lbarry-apsl @mpascuall @javierobcn Please review.

[@APSL](https://github.com/APSL) cc 155114

### CODE REVIEW

**Review by peluko00 — APPROVED** [review]
Works good, tested in runboat.
Very good and useful module

**Review by lbarry-apsl — APPROVED** [review]
Tested on Runboat

**Comment by lbarry-apsl** [comment]
@miquelalzanillas ,

I think it would be better if the analytic accounts filter showed a table where you could indicate what percentage goes into each analytical account.

**Comment by miquelalzanillas** [comment]
> @miquelalzanillas ,
> 
> I think it would be better if the analytic accounts filter showed a table where you could indicate what percentage goes into each analytical account.

Thanks for the feedback.

Percentage distribution is not the purpose of this module, as this functionality is natively implemented from version 16 with the new analytic distribution feature. The main objective of this module is to automatically distribute account move lines among several analytic accounts without the need to specify each account individually (along with a percentage).

This module is useful when landing costs analytic lines need to be created massively on some analytic accounts related to departments or projects

Is true that right now is only covering one formula ( move_line.amount / _N_ analytic accounts) and could be interesting to implement other formulas in the future.

**Comment by pedrobaeza** [comment]
You can put it in the ROADMAP.

**Review by mpascuall — APPROVED** [review]
Works good, checked in runboat

**Comment by miquelalzanillas** [comment]
Hi @pedrobaeza , just added the ROADMAP.

Could you please review and check if is ready to merge? 

Thanks.

**Pull request merged**
