### PR TITLE
[16.0][ADD] hr_timesheet_analytic_tag: New module

### PR DESCRIPTION
**Pull request by victoralmau**
New module

Please @pedrobaeza can you review it?

@Tecnativa TT42272

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I'm not getting the sense of this module. There were no analytic tags previously.

**Comment by victoralmau** [comment]
This functionality does exist in v15 in `project` (https://github.com/odoo/odoo/blob/15.0/addons/project/models/project.py#L1160).
ejemplo-v15

This field is useful when adding timesheets (with the `hr_timesheet` module), these analytical tags are defined. This functionality will be done in another module `hr_timesheet_analytic_tag` that depends on this one.

**Comment by pedrobaeza** [comment]
Please do it in the last module and not in 2 then.

**Comment by victoralmau** [comment]
Ok, renamed to `hr_timesheet_analytic_tag` and added all necessary changes.

**Review by pedrobaeza — APPROVED** [review]

**Comment by victoralmau** [comment]
Ping @chienandalu

**Review by chienandalu — APPROVED** [review]

**Pull request merged**
