### PR TITLE
[12.0][IMP] missing account analytic in MO created from SO with module mrp_analytic

### PR DESCRIPTION
**Pull request by sergiocorato**
#320

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Code makes sense to me. Could you include the module name in the title? Just for better searching. Thank you!

**Comment by sergiocorato** [comment]
=( sorry no test as I haven't found a way to install a module (`sale_management`) inside the test to test the MO creation.

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tested :+1:  Please squash your commits

**Review by jpcarassato — APPROVED** [review]
Test OK!

**Review by marcelsavegnago — APPROVED** [review]

**Comment by sergiocorato** [comment]
Commits squashed!

**Pull request merged**
