### PR TITLE
[16.0][MIG] analytic_base_department

### PR DESCRIPTION
**Pull request by hbrunn**
/ocabot migration analytic_base_department

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
LGTM

**Review by peluko00 — APPROVED** [review]
LGTM

**Review by BernatObrador — APPROVED** [review]
LGTM

**Review by ppyczko — APPROVED** [review]
LGTM

**Comment by peluko00** [comment]
Seems is ready to merge @pedrobaeza ?

**Pull request merged**
