### PR TITLE
[13.0][MIG] purchase_request_analytic

### PR DESCRIPTION
**Pull request by ps-tubtim**
This PR is waiting for https://github.com/OCA/purchase-workflow/pull/804, you can always use this for readability.

- [x] [13.0][MIG] purchase_request

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
If seems there are conflicts in oca_dependencies.txt file. Could you check?

**Comment by ps-tubtim** [comment]
> If seems there are conflicts in oca_dependencies.txt file. Could you check?

@AaronHForgeFlow Thank you. I resolved conflicts.

**Review by AaronHForgeFlow — APPROVED** [review]
@ps-tubtim Thanks. Tested on local and works good! :+1:

**Pull request merged**
