### PR TITLE
[16.0][IMP] stock_analytic: salvage analytic distribution from procurement

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
@qrtl QT4346

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review.

**Review by yostashiro — APPROVED** [review]
Code review.

**Comment by StefanRijnhart** [comment]
Is it perhaps the case that this is the same issue that is solved in the 17.0 migration using `_get_custom_move_fields`? See https://github.com/OCA/account-analytic/pull/614/commits/fa50c404e9a89e43bb5ea1c65a9ff1166180cde5, included in https://github.com/OCA/account-analytic/pull/614). If so, isn't using that entry point more appropriate?

**Comment by yostashiro** [comment]
> Is it perhaps the case that this is the same issue that is solved in the 17.0 migration using `_get_custom_move_fields`? See [fa50c40](https://github.com/OCA/account-analytic/commit/fa50c404e9a89e43bb5ea1c65a9ff1166180cde5), included in #614). If so, isn't using that entry point more appropriate?

Thanks! The suggested approach does look better indeed. @AungKoKoLin1997

**Comment by StefanRijnhart** [comment]
@AungKoKoLin1997  thanks for the update! Can you credit @aisopuro as a co-author of the commit? (see https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-the-command-line)

**Review by StefanRijnhart — APPROVED** [review]
Thanks for the follow-up!

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
