### PR TITLE
[10.0][FIX] .travis: Postgresql version

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please take the occasion to reduce 1 Travis build and put MAKEPOT in the other.

**Comment by Cedric-Pigeon** [comment]
@pedrobaeza I m not used to travis... Could you provide me with a sample pls?

**Comment by pedrobaeza** [comment]
https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml

**Comment by Cedric-Pigeon** [comment]
@pedrobaeza Thanks. Done.

**Review by pedrobaeza — APPROVED** [review]
Fast-tracking this

**Pull request merged**
