### PR TITLE
[14.0][ADD] stock_picking_type_analytic

### PR DESCRIPTION
**Pull request by rousseldenis**
Depends on:

- [ ] #406

### CODE REVIEW

**Comment by rousseldenis** [comment]
@rafaelbn Could you reopen this one ?

**Comment by rafaelbn** [comment]
Hello @rousseldenis , Github don't allow me to open! I don't know why...

**Comment by rafaelbn** [comment]
Let's try again!

**Comment by rafaelbn** [comment]
So the goood one is this one: https://github.com/OCA/account-analytic/pull/486

**Pull request closed without merging**
