### PR TITLE
[16.0][IMP] purchase_stock_analyic: propagates values when values are changed even after confirmed PO

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
This PR propagates the values from PO lines to related stock moves when values are updated after confirmed the PO.

@qrtl

### CODE REVIEW

**Review by yostashiro — APPROVED** [review]
Code review.

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Comment by AungKoKoLin1997** [comment]
@OCA-account-analytic-maintainers
Can we get this PR merged?

**Pull request merged**
