### PR TITLE
[14.0] Migration account_analytic_sequence

### PR DESCRIPTION
**Pull request by petrus-v**
migrated from v12.0

### CODE REVIEW

**Comment by petrus-v** [comment]
This new constraint is breaking `account_analytic_parent` unittest  is it the way to go to fix that in the same PR ? or is there a way to tell two modules are incompatible in the same repository ?

**Comment by petrus-v** [comment]
> This new constraint is breaking `account_analytic_parent` unittest is it the way to go to fix that in the same PR ? or is there a way to tell two modules are incompatible in the same repository ?

I've cherry-picked travis config from @ps-tubtim (thanks) used in #271 waiting CI results !

**Review by ps-tubtim — APPROVED** [review]
LGTM

**Review by manuelregidor — APPROVED** [review]
LGTM

**Pull request merged**
