### PR TITLE
[15.0][IMP] account_move_update_analytic: hide button column when not posted

### PR DESCRIPTION
**Pull request by ghost**
@remi-filament @Shide 
I changed the view slightly to hide the button column when the account move is not posted.

### CODE REVIEW

**Comment by ghost** [comment]
What do you think about setting the default new values = current values?
Then the user can change what should change, and the rest will be the same as before.
I did this in a new commit now.

**Review by Shide — APPROVED** [review]
LGTM, just fix the pre-commit issue

**Review by remi-filament — APPROVED** [review]
Thanks, looks better now

**Comment by rafaelbn** [comment]
Please @appstogrow , fix the pre-commit issue 😄 thank you! after that we can merge!

**Comment by norlinhenrik** [comment]
@rafaelbn I don't understand the pre-commit error message. Could you please have a look? Do you think it is related to this PR?

**Comment by Shide** [comment]
It's ok for me. The pre-commit issue cannot be fixed by us and the code is well pre-commited.
@rafaelbn if you can merge... :)
LGTM

**Review by rafaelbn — APPROVED** [review]
/ocabot merge minor

**Pull request merged**
