### PR TITLE
[12.0][FIX] stock_analytic apply AA on COGS account in customer invoice

### LINKED ISSUE #284: [11.0/12.0] Stock analytic
Hi all,

I think this commit:
https://github.com/odoo/odoo/commit/24c7efc8fef63437ac28883b29ed84809234ed76

Will break functionality of the module stock analytic?

Since the booking for the stock_account_output from the customer invoice will not contain an analytic account, the analytic account will never be balanced?

@max3903 @AaronHForgeFlow

### PR DESCRIPTION
**Pull request by CasVissers-360ERP**
[12.0][FIX] stock_analytic apply AA on COGS account in customer invoice

Fixes #284

Tested with:
http://3407167-286-ec1a89.runbot2-2.odoo-community.org/web?debug=true#id=10&model=account.move&view_type=form&menu_id=250

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Thanks for this PR. It seems there is some strange error when logging in on runbot, kinda syntax error in python code or so. I will test this on local.

**Comment by CasVissers-360ERP** [comment]
@AaronHForgeFlow 
Reminder

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional test. Could you fix lint error?

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by CasVissers-360ERP** [comment]
@AaronHForgeFlow 
No idea how to fix the lint error, can you give me some directions?

**Comment by AaronHForgeFlow** [comment]
@CasVissers It seems to me it is only the 79 character limit per line. Some lines are longer.

**Comment by CasVissers-360ERP** [comment]
@AaronHForgeFlow 
Thnx, I tried to fix it, let's see.

**Comment by AaronHForgeFlow** [comment]
Almost, now it is indentation lint error :(

`stock_analytic/models/product_product.py:30:45: E126 continuation line over-indented for hanging indent`

**Comment by AaronHForgeFlow** [comment]
FYI  I squashed your commits into one. Ready to merge when green.

**Comment by CasVissers-360ERP** [comment]
@AaronHForgeFlow 
Green!

**Pull request merged**
