### PR TITLE
[15.0][mig]-purchase_request_analytic

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
@ForgeFlow

Re-open https://github.com/OCA/account-analytic/pull/466

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
I think you can take the advantage a do a refactor in this module. Same as it was done with the purchase_analytic module here: https://github.com/OCA/account-analytic/pull/478

**Comment by JuanyDForgeflow** [comment]
@AaronHForgeFlow please check now

**Comment by AaronHForgeFlow** [comment]
purchase_request_analytic

Hi @JuanyDForgeflow On the creation it does not fill the analytic account in the lines, it works after it is saved. Is it possible to fix that?

**Comment by JuanyDForgeflow** [comment]
@AaronHForgeFlow please review now

**Comment by AaronHForgeFlow** [comment]
Hi @JuanyDForgeflow  It seems that the analytic account field is now readonly in the lines, but they should be editable. Can you check?

**Comment by AaronHForgeFlow** [comment]
> Hi @JuanyDForgeflow It seems that the analytic account field is now readonly in the lines, but they should be editable. Can you check?

still this problem, all the rest works good.

**Comment by JasminSForgeFlow** [comment]
> > Hi @JuanyDForgeflow It seems that the analytic account field is now readonly in the lines, but they should be editable. Can you check?
> 
> still this problem, all the rest works good.

it is fixed, Thanks

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests LGTM :+1:

**Review by LoisRForgeFlow — APPROVED** [review]
Code review LGTM :+1:

**Pull request merged**
