### PR TITLE
[15.0][mig] analytic_tag_dimension_enhanced

### PR DESCRIPTION
**Pull request by TheerayutEncoder**
Standard migration :+1:

### CODE REVIEW

**Comment by TheerayutEncoder** [comment]
@newtratip @Saran440 
Can you help review ?
Thanks.

**Comment by ps-tubtim** [comment]
@TheerayutEncoder Please separate the commits following https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0 and add you to `CONTRIBUTORS.rst`.

**Review by Saran440 — APPROVED** [review]
No code change :+1:

**Comment by Saran440** [comment]
I enhanced this module for easy some module don't need required
Selection_016

In case, we need required analytic tags somewhere not all.
This commit will can exclude filter for not required analytic tags

**Review by ps-tubtim — APPROVED** [review]
LGTM

**Pull request closed without merging**
