### PR TITLE
[18.0][MIG] analytic_base_department: Migration to 18.0 

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 18.0

cc https://github.com/APSL 163708
@miquelalzanillas @javierobcn @mpascuall @BernatObrador @ppyczko please review

- [Issue] https://github.com/OCA/account-analytic/issues/696

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
LGTM, tested in runboat

**Review by ppyczko — APPROVED** [review]
LGTM!

**Review by BernatObrador — APPROVED** [review]
LGTM

**Review by houssine78 — APPROVED** [review]

**Comment by houssine78** [comment]
@pedrobaeza this one is ready for merging too

**Review by dreispt — APPROVED** [review]

**Pull request merged**
