### PR TITLE
[MIG] product_analytic: Migration to 16.0

### PR DESCRIPTION
**Pull request by CLaurelB**

### CODE REVIEW

**Comment by CLaurelB** [comment]
@desdelinux @luisg123v could you review, please?

**Review by desdelinux — APPROVED** [review]

**Comment by desdelinux** [comment]
Please, review

@dreispt @rafaelbn @CasVissers-360ERP @rousseldenis

**Review by fcvalgar — APPROVED** [review]
Functional review,
LGTM, Thank you @CLaurelB 

image

image

image

image

**Comment by fcvalgar** [comment]
@rafaelbn pending merge

**Pull request merged**
