### PR TITLE
[16.0][MIG] account_analytic_root

### PR DESCRIPTION
**Pull request by victor-champonnois**
Back-ported to 12 in https://github.com/OCA/account-analytic/pull/612
Add a top parent for analytic account, for reporting purposes.

### CODE REVIEW

**Comment by victor-champonnois** [comment]
@robinkeunen

**Review by robinkeunen — CHANGES_REQUESTED** [review]
Migration is ok but I have the same reserves as in #612 

By labelling this PR [ADD] and label #612 as a backport, you might get more attention.

**Comment by victor-champonnois** [comment]
@robinkeunen changed the PR name as you suggested and fixed the test.

**Review by robinkeunen — APPROVED** [review]

**Comment by victor-champonnois** [comment]
renamed to `account_analytic_root` (see discussion https://github.com/OCA/account-analytic/pull/612)

**Comment by AaronHForgeFlow** [comment]
Sorry for the nitpicking @victor-champonnois but the related model should be in the name of the field, as it is a Many2one. It should be root_analytic_account_id.

**Comment by victor-champonnois** [comment]
@AaronHForgeFlow Changed the name as you suggested.

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM! What about displaying the root analytic account in the form view?

**Pull request merged**
