### PR TITLE
[16.0][IMP] stock_analytic: add validation on analytic distribution

### PR DESCRIPTION
**Pull request by yostashiro**
To follow up on https://github.com/OCA/account-analytic/pull/506#issuecomment-1375161004.

- Add validation on analytic distribution according to how it is done in other models (account.move.line, sale.order.line, etc.).
- Update readme to reflect the current design.
- Other cosmetic adjustments.

@qrtl

### CODE REVIEW

**Review by kanda999 — APPROVED** [review]
Function review:
Analystic description validated in stock.picking

**Review by AungKoKoLin1997 — APPROVED** [review]
Function review:
Tested in runboat. It worked as expected.

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LGTM. Thanks for the fix.

**Comment by AaronHForgeFlow** [comment]
Just one last comment before the merge. I tried to validate a picking for a product with automated inventory valuation and with a stock move with the analytic distribution set I get the validation error "One or more lines require a 100% analytic distribution." I am not sure if it is an actual issue or a misconfiguration in the analytic plan or it is an actual issue. Does that make sense? here is the link to the picking in runboat: http://oca-account-analytic-16-0-pr528-06cc4c3c2c31.runboat.odoo-community.org/web?debug=1#id=39&cids=1&menu_id=168&action=319&active_id=1&model=stock.picking&view_type=form

**Comment by yostashiro** [comment]
@AaronHForgeFlow I suppose that was coming from the mandatory default applicability set on a plan.
image

I guess this would try to do a validation on the generated account move lines (not on the stock moves where we make incoming moves out of validation scope), and therefore the validation error.  I just changed the default applicability of the plan to optional and I was able to validate the incoming picking.

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review

**Comment by AaronHForgeFlow** [comment]
I think 3 weeks is enough time for others to give their opinions and this is about to be merged now.

**Pull request merged**
