### PR TITLE
[15.0][MIG] pos_analytic_by_config: Migration to 15.0.

### PR DESCRIPTION
**Pull request by Ricardoalso**

### CODE REVIEW

**Review by ivantodorovich — COMMENTED** [review]
Code LG but ci is red 🤔

**Comment by Ricardoalso** [comment]
> Code LG but ci is red thinking

I didn't have time to investigate further for now, but 15.0 branch seems to be broken with the same tests failing since a long time

**Review by leemannd — APPROVED** [review]
Thank you

**Review by Highcooley — APPROVED** [review]
LG functionally

**Pull request merged**
