### PR TITLE
[REF][IMP][FIX] account_analytic_wip: use actuals to post WIP, dont post variances until Close

### PR DESCRIPTION
**Pull request by dreispt**
- [CHG] account_analytic_wip: consume raw materials when posting WIP
- [IMP] account_analytic_wip: UI improvements

### CODE REVIEW

**Comment by dreispt** [comment]
@RLeeOSI You installed and tested this. Can you add a review please?

**Comment by RLeeOSI** [comment]
@dreispt  I've tested and it LGTM. Our customer is going to be functionally testing this soon, hopefully this week. I can leave a review now, or wait to see if they find any issues

**Comment by dreispt** [comment]
@RLeeOSI IMO merging sooner is better, as basic functionality has been validated. Any future fixes can be added anytime.

**Comment by patrickrwilson** [comment]
@dreispt there are a lot of commits, is that to show the historical changes? If not can you squash. Also are you planning on increasing codecov?

**Comment by dreispt** [comment]
@patrickrwilson It could ease review if familiar with the original code. I can squash my commits.
I feel that code coverage is decent, and I'm not planning to add more tests at this point.

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Pull request merged**
