### PR TITLE
[15.0][FIX] account_move_update_analytic: Switch button text to icon

### PR DESCRIPTION
**Pull request by Shide**
Button text is super large and doesn't fit well on any screen. Also is pretty ugly

Replace the button text with a pretty icon `fa-tags` and add a proper title to know what is going to happen if you click the button.
Also added maintainers

I pretend to FWP this commit into 16.0 once it's merged.

MT-3838 @moduon @yajo @rafaelbn @EmilioPascual @remi-filament plz review if you want 😄

### CODE REVIEW

**Comment by EmilioPascual** [comment]
LGTM

**Review by EmilioPascual — APPROVED** [review]

**Review by yajo — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
👍🏼 

Check before and after 🥳 

imagen


Ping @remi-filament

**Review by remi-filament — APPROVED** [review]
Makes sense, it is much better looking that way !
Thanks

**Comment by remi-filament** [comment]
> I pretend to FWP this commit into 16.0 once it's merged.

I do not think this module is necessary in v16.0 since you can already update analytic distribution !

**Pull request merged**
