### PR TITLE
[18.0][MIG] account_analytic_tag: Migration to 18.0

### PR DESCRIPTION
**Pull request by mpascuall**
Module migrated to version 18.0

cc https://github.com/APSL 163426
@miquelalzanillas @lbarry-apsl @javierobcn @peluko00  @BernatObrador @ppyczko please review

[Issue] https://github.com/OCA/account-analytic/issues/696

### CODE REVIEW

**Review by peluko00 — APPROVED** [review]
LGTM, tested in runboat

**Review by BernatObrador — APPROVED** [review]
LGTM code review + test in runboat

**Review by miquelalzanillas — APPROVED** [review]
Code review. LGTM.

Hi @pedrobaeza ,

Can you do a check here and see if can be merged?

Thanks.

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration account_analytic_tag
/ocabot merge nobump

**Pull request merged**
