### PR TITLE
[15.0] [FIX] Moved merging check from purchase order level to line level. (#217)

### PR DESCRIPTION
**Pull request by airlessproject**
This commit was removed from history moving from v11 to v15. It had the following ref: e3f0a8214699c3b35486fb62a89261e4ece040cb 

It moves the checking for mergeability of PO lines from PO level to line level.
The result will be that MTO lines that come from Sale Orders with different 
analytic accounts, now will be put in the same Purchase Order, but in different
PO lines. If the analytic accounts are the same (or none), they will be merged
in one PO line.
Without this commit, for Sale Orders with different analytic accounts, it will always
create new PO for the second PO line.

@carlosdauden @pedrobaeza @cubells please check

### CODE REVIEW

**Comment by rousseldenis** [comment]
@airlessproject FYI, I've done something more clever there : https://github.com/OCA/account-analytic/pull/413/commits/12bd16ce32eecdd5d0ddc8a1f51002e03904b1b7

You can select the default behaviour as an option.

**Comment by airlessproject** [comment]
> @airlessproject FYI, I've done something more clever there : [12bd16c](https://github.com/OCA/account-analytic/commit/12bd16ce32eecdd5d0ddc8a1f51002e03904b1b7)
> 
> You can select the default behaviour as an option.

@rousseldenis it looks good, thanks for the info. But seems this module purchase_procurement_analytic is not in 15.0 code, is there a PR to put it into 15.0 somewhere? Thanks!

**Comment by rousseldenis** [comment]
> > @airlessproject FYI, I've done something more clever there : [12bd16c](https://github.com/OCA/account-analytic/commit/12bd16ce32eecdd5d0ddc8a1f51002e03904b1b7)
> > You can select the default behaviour as an option.
> 
> @rousseldenis it looks good, thanks for the info. But seems this module purchase_procurement_analytic is not in 15.0 code, is there a PR to put it into 15.0 somewhere? Thanks!

Mmmh, looking at code, I would say that there are code duplicates in both modules.

IMHO, procumrent_mto_analytic should depends on procurement_purchase_analytic and remove all code duplicate.

**Comment by airlessproject** [comment]
> > > @airlessproject FYI, I've done something more clever there : [12bd16c](https://github.com/OCA/account-analytic/commit/12bd16ce32eecdd5d0ddc8a1f51002e03904b1b7)
> > > You can select the default behaviour as an option.
> > 
> > 
> > @rousseldenis it looks good, thanks for the info. But seems this module purchase_procurement_analytic is not in 15.0 code, is there a PR to put it into 15.0 somewhere? Thanks!
> 
> Mmmh, looking at code, I would say that there are code duplicates in both modules.
> 
> IMHO, procumrent_mto_analytic should depends on procurement_purchase_analytic and remove all code duplicate.

Nevertheless, as I see, the procurement_purchase_analytic is still on 10.0 branch. Do we have a PR that migrates it to 15.0, and afterwards it may be checked for duplicate code against procurement_mto_analytic, or maybe it's best to merge both modules in one. But again I must observe that procurement_mto_analytic is currently at 15.0 and this PR fixes this issue that's addressed in procurement_purchase_analytic even better, but here it is a bug IMO.

**Comment by rousseldenis** [comment]
> > > > @airlessproject FYI, I've done something more clever there : [12bd16c](https://github.com/OCA/account-analytic/commit/12bd16ce32eecdd5d0ddc8a1f51002e03904b1b7)
> > > > You can select the default behaviour as an option.
> > > 
> > > 
> > > @rousseldenis it looks good, thanks for the info. But seems this module purchase_procurement_analytic is not in 15.0 code, is there a PR to put it into 15.0 somewhere? Thanks!
> > 
> > 
> > Mmmh, looking at code, I would say that there are code duplicates in both modules.
> > IMHO, procumrent_mto_analytic should depends on procurement_purchase_analytic and remove all code duplicate.
> 
> Nevertheless, as I see, the procurement_purchase_analytic is still on 10.0 branch. Do we have a PR that migrates it to 15.0, and afterwards it may be checked for duplicate code against procurement_mto_analytic, or maybe it's best to merge both modules in one. But again I must observe that procurement_mto_analytic is currently at 15.0 and this PR fixes this issue that's addressed in procurement_purchase_analytic even better, but here it is a bug IMO.

You can review the 14.0's PR: https://github.com/OCA/account-analytic/pull/413

**Comment by airlessproject** [comment]
> > > > > @airlessproject FYI, I've done something more clever there : [12bd16c](https://github.com/OCA/account-analytic/commit/12bd16ce32eecdd5d0ddc8a1f51002e03904b1b7)
> > > > > You can select the default behaviour as an option.
> > > > 
> > > > 
> > > > @rousseldenis it looks good, thanks for the info. But seems this module purchase_procurement_analytic is not in 15.0 code, is there a PR to put it into 15.0 somewhere? Thanks!
> > > 
> > > 
> > > Mmmh, looking at code, I would say that there are code duplicates in both modules.
> > > IMHO, procumrent_mto_analytic should depends on procurement_purchase_analytic and remove all code duplicate.
> > 
> > 
> > Nevertheless, as I see, the procurement_purchase_analytic is still on 10.0 branch. Do we have a PR that migrates it to 15.0, and afterwards it may be checked for duplicate code against procurement_mto_analytic, or maybe it's best to merge both modules in one. But again I must observe that procurement_mto_analytic is currently at 15.0 and this PR fixes this issue that's addressed in procurement_purchase_analytic even better, but here it is a bug IMO.
> 
> You can review the 14.0's PR: #413

Thanks!

**Comment by airlessproject** [comment]
As agreed, after https://github.com/OCA/account-analytic/pull/413 is merged, the code in this module should be reworked and the duplicate code that is already in `purchase_procurement_analytic` should be removed, and this module should be made dependent on it. That should be done in 14.0 and 15.0 as well.

**Pull request closed without merging**
