### PR TITLE
[13.0][mig] analytic_tag_dimension_sale_warning

### PR DESCRIPTION
**Pull request by captivea-dcr**
superseeds #300

### CODE REVIEW

**Comment by baimont** [comment]
Functional testing: ko

To reproduce:
The warning message is there, so the module works. But it misses something.
image

Problem is, when you save above sale order, you get:
ValueError: Invalid field 'x_dimension_type' on model 'sale.order.line'

What is missing here is an inheritance of `get_model_names()` method on `account.analytic.dimension` in order to append `sale.order.line` to model names. This method is called whenever you create or write on a dimension to create or update the field in said model.

I haven't checked, but the problem should arise too for
https://github.com/OCA/account-analytic/pull/313
https://github.com/OCA/account-analytic/pull/300
https://github.com/OCA/account-analytic/pull/299

**Review by baimont — APPROVED** [review]
functional testing ok

**Review by kittiu — APPROVED** [review]
LGTM

**Pull request merged**
