### PR TITLE
[15.0][MIG] account_analytic_parent

### PR DESCRIPTION
**Pull request by Dariosi**

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
I think the balance should be positive in this example. Am I wrong?

image

**Comment by Dariosi** [comment]
@AaronHForgeFlow 
In this case balance of analytic account is calculated correctly.

Analytic accounts are about costs/expences (debit) and revenues/income (credit).
Negative balance means expences.

Module `account_analytic_parent` does not change the logic of balance calculation for analytic accounts.
The same balance logic is used in module `analytic`: https://github.com/odoo/odoo/blob/15.0/addons/analytic/models/analytic_account.py#L124

**Comment by AaronHForgeFlow** [comment]
yes, sorry for the noise

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review

**Review by gaikaz — APPROVED** [review]
Code review

**Review by Mantux11 — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Retrying the merge, it seems the build failed because of an infrastructure thing

/ocabot merge nobump

**Pull request merged**
