### PR TITLE
[MIG] account_analytic_distribution: Migration to 11.0

### PR DESCRIPTION
**Pull request by cubells**
cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@danger89 @yvaucher can you re-review this one without CI errors?

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
@cubells don't change copyright years of untouched files

**Comment by pedrobaeza** [comment]
@cubells please finish this

**Comment by cubells** [comment]
@pedrobaeza done.

**Review by pedrobaeza — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
Tested functionally in runbot :+1:

**Pull request merged**
