### PR TITLE
[12.0] [MIG] analytic_product_category

### PR DESCRIPTION
**Pull request by anandkansagra**
Issue [Reference](https://github.com/OCA/account-analytic/issues/189)

### CODE REVIEW

**Comment by HaraldPanten** [comment]
Just a comment @anandkansagra ,

About the bot reminder: I already sent my CLA

**Comment by anandkansagra** [comment]
> Just a comment @anandkansagra ,
> 
> About the bot reminder: I already sent my CLA

@oca-clabot , Could you please look it out?

**Comment by spacimek** [comment]
Can someone please merge this to v12? It seems like all checks were passed long time ago, but it's still missing in 12.0 branch. Thanks!

**Comment by ovnicraft** [comment]
LGTM

**Review by ovnicraft — APPROVED** [review]

**Review by HaraldPanten — APPROVED** [review]

**Review by ps-tubtim — APPROVED** [review]

**Pull request merged**
