### PR TITLE
[15.0] Migration of procurement_mto_analytic

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

Migration PR for module procurement_mto_analytic.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### CODE REVIEW

**Review by olveracuenca — APPROVED** [review]

**Review by ibraimFer — APPROVED** [review]
Complete this migration

**Review by olveracuenca — APPROVED** [review]
10/10

**Review by MiguelJarsa — APPROVED** [review]
This is great

**Review by MiguelJarsa — APPROVED** [review]
this migration looks good

**Review by marco1esparza — APPROVED** [review]
full migration to version 15.0

**Review by marco1esparza — APPROVED** [review]
Complete migration to version 15.0, good implementation

**Comment by rousseldenis** [comment]
@alan196 Thanks for this

@marco1esparza Thanks not spamming the PR.

**Review by rousseldenis — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
it failed because setupools when building the instance, let's try again:
/ocabot migration procurement_mto_analytic
/ocabot merge nobump

**Pull request merged**
