### PR TITLE
[11.0][MIG]account analytic sequence

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
No changes required.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Comment by AaronHForgeFlow** [comment]
IMHO this can be merged

**Review by espo-tony — APPROVED** [review]
:+1:

**Comment by AaronHForgeFlow** [comment]
Is is possible to merge this one?

**Review by ThomasBinsfeld — APPROVED** [review]

**Pull request merged**
