### PR TITLE
[16.0][MIG] account_move_update_analytic

### PR DESCRIPTION
**Pull request by hbrunn**
migration of [account_move_update_analytic](https://github.com/OCA/account-analytic/tree/15.0/account_move_update_analytic#account-move-update-analytic)

### CODE REVIEW

**Comment by rousseldenis** [comment]
@hbrunn Could you squash your commits and rebase ?

**Comment by hbrunn** [comment]
@rousseldenis thanks, done

**Review by rousseldenis — APPROVED** [review]
Code and functional review

**Review by rafaelbn — COMMENTED** [review]
Hello @hbrunn !

Thank you!

I miss the option in 14 and 15 for updating from the invoice, see:

imagen


In this PR is missing

imagen

**Comment by hbrunn** [comment]
this lives in the journal items tab, seemed more logical to me

**Comment by rafaelbn** [comment]
Hello @hbrunn ,

> this lives in the journal items tab, seemed more logical to me

I repect really, but we don't make software more logical for us, we make for accountants and in general users.

Users expect in the lines and not in other tab

- more clics
- different place to update than the place you set <- illogic


Please, keep it in the place it was 🙏🏼 it was analysed with different accountants from different clients before decisions. I mean is a conscious product decision.

Le me know 😄 

Thank you!
Best regards,
Rafael

**Comment by hbrunn** [comment]
@rafaelbn moved it back to where it was, will then do the "more logical" part in my customer's private module ;-)

**Review by rafaelbn — APPROVED** [review]
Thank you @hbrunn ! 👍🏼 

I really will still ask for more point of view, thank you ❤️ 

imagen

**Review by EmilioPascual — APPROVED** [review]
LGTM

**Comment by gjlong68** [comment]
miss analytic tags
image

**Comment by rafaelbn** [comment]
Hello @hbrunn !

Just to inform you, this module is not needed any more in Odoo 16 to update from move lines (journal items) because Odoo allow it in the list view with multi-edit.

**Then need of this module is only if you need to update analytic from invoices exclusively**. I mean a Billing user that doesn't have access to full accounting.

😄 

@gjlong68 , Odoo 16 don't have un core anymore analytic tags, so a new module is needed for that depending in the OCA module which adds again the analytic tags. Not aplicable in this module.

Ping @remi-filament !!!

**Pull request merged**
