### PR TITLE
[16.0][FIX] stock_analytic

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
This PR fixes analytic_distribution not being passed from move to move line when updated after the move line is created.

@qrtl QT4873

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LGTM

**Review by yostashiro — APPROVED** [review]
Code review.

**Comment by AungKoKoLin1997** [comment]
@oca/account-analytic-maintainers
Can we get this PR merged?

**Review by AaronHForgeFlow — APPROVED** [review]
/ocabot merge minor

**Comment by AaronHForgeFlow** [comment]
Could you please forward port this to v17?

**Comment by AungKoKoLin1997** [comment]
> Could you please forward port this to v17?

@AaronHForgeFlow I created the PR https://github.com/OCA/account-analytic/pull/706.

**Pull request merged**
