### PR TITLE
[FIX][8.0] analytic_multicurrency: Fixed 'quantity' key error

### PR DESCRIPTION
**Pull request by Daniel-CA**
Fixed bug reported in #169

### CODE REVIEW

**Comment by Daniel-CA** [comment]
@pedrobaeza Can you merge this one?

**Review by pedrobaeza — APPROVED** [review]
OK, as this a low risk PR, I'll fast-track it, but 2 reviews are usually needed

**Comment by fdvarela** [comment]
@pedrobaeza Just tested it on my installation and fixes the former programming error. It's a go.

**Comment by pedrobaeza** [comment]
@fdvarela then next time please put your proper review in the PR.

**Comment by Daniel-CA** [comment]
Thanks @pedrobaeza

**Pull request merged**
