### PR TITLE
[FIX][8.0] Fix travis error

### PR DESCRIPTION
**Pull request by andhit-r**
All travis fixes

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please do it in the same PR all

**Comment by pedrobaeza** [comment]
Please rebase this because .travis.yml was incorrect.

**Comment by andhit-r** [comment]
Done @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
Thanks for taking care of this. I fast-track to fix the branch.

**Pull request merged**
