### PR TITLE
[14.0][ADD] account_analytic_required_never

### PR DESCRIPTION
**Pull request by rousseldenis**
When creating account move lines, don't fill in analytic account (even if passed in parameters) if analytic policy is set to 'Never'

### CODE REVIEW

**Comment by rousseldenis** [comment]
@sanrav @adrienpeiffer

**Review by adrienpeiffer — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
@OCA/accounting-maintainers

**Comment by rafaelbn** [comment]
I don't understand the difference with https://github.com/OCA/account-analytic/blob/14.0/account_analytic_required/models/account.py#L17

```
    property_analytic_policy = fields.Selection(
        selection=[
            ("optional", "Optional"),
            ("always", "Always"),
            ("posted", "Posted moves"),
            ("never", "Never"),
``` 

The question is:

- Without this module if account_analytic_required is set to "never" and the analytic account is set then de account.move has analytic
- With this module if account_analytic_required is set to "never" and the analytic account is set then de account.move has NOT analytic


Is it?

Thank you!

**Pull request closed without merging**
