### PR TITLE
[14.0][MIG] account_analytic_required

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
Functional test 👍

**Comment by leemannd** [comment]
Migration work seems legit but failing on https://travis-ci.com/github/OCA/account-analytic/jobs/442334044#L364
@alexis-via do you have time to take a look at the pre-commit error?

**Review by leemannd — APPROVED** [review]

**Review by hildickethan — APPROVED** [review]
Functional review

**Comment by jonathanBouygues** [comment]
functionnal review

**Review by jonathanBouygues — APPROVED** [review]

**Comment by rousseldenis** [comment]
@alexis-via The odoo code has changed in the meantime.

See https://github.com/odoo/odoo/commit/80c28189ae6b10ad17c4de2a781233a8ffe663a6#diff-1e3bd6be3bfb83a37ec9fb800ce8b1c95afe0be90ff792874ae7299c320a2f6eR2431

**Comment by dreispt** [comment]
Tests are failing https://travis-ci.com/github/OCA/account-analytic/jobs/506877220#L1622

**Comment by desdelinux** [comment]
@alexis-via your revision, please

**Review by victoralmau — APPROVED** [review]
Code review OK

**Pull request merged**
