### PR TITLE
[14.0][FIX] analytic_tag_dimension_enhanced: not check required dimension in non-invoice

### PR DESCRIPTION
**Pull request by ps-tubtim**
### Setting:
- Create analytic accounts dimensions
- Check **Require** in analytic accounts dimension

Selection_164

### Before Fix: Error when create payment
Selection_165

### After Fix: Can create payment
Selection_166

### CODE REVIEW

**Review by Saran440 — APPROVED** [review]
Functional Test, LGTM :+1: 

BUT test script error. Could you fix it. @ps-tubtim

**Review by Saran440 — CHANGES_REQUESTED** [review]
Travis is red.

**Comment by kittiu** [comment]
ping @ps-tubtim

**Review by Saran440 — APPROVED** [review]

**Pull request merged**
