### PR TITLE
[11.0][MIG] stock_analytic 

### PR DESCRIPTION
**Pull request by jaredkipe**
Tests passed with minor changes (11.0 specific needs).
I currently use this in something that makes stock moves on its own, and it works perfectly fine, however...

There is a UX problem in Odoo 11.0 as there is no good way to modify the stock move created on a picking to have an analytic account. I think I should add that to the current tree view (on the picking) to the left of the 'Initial Demand' field.

( better #161 )

### CODE REVIEW

**Comment by jaredkipe** [comment]
I'll be adding a view to expose/pick the analytic account on the picking's move line tree in the near future (probably today).

**Review by AaronHForgeFlow — APPROVED** [review]
Tested on local LGTM :+1:

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Comment by AaronHForgeFlow** [comment]
@jaredkipe can you squash a bit your commits? Thanks!

**Review by CasVissers-360ERP — APPROVED** [review]
LGTM

**Comment by CasVissers-360ERP** [comment]
@jaredkipe 
`        for num in range(0, 2):
            if res[num][2]["account_id"] != self.product_id.\
                    categ_id.property_stock_valuation_account_id.id:
                res[num][2].update({
                    'analytic_account_id': self.analytic_account_id.id,
                })
        return res
`

This function doesn't seem to work. I get an analytic account in both the debit & credit move line. Should be only in the debit line.

EDIT:
@jaredkipe Seems like I configured some settings wrongly. Working now. Functional test ok.

**Comment by AaronHForgeFlow** [comment]
Hi @jaredkipe this is about to be merged. Can you squash a bit some of the commits with similar content(flake8, transifex, etc)?

**Comment by jaredkipe** [comment]
@aheficent All done!

**Pull request merged**
