### PR TITLE
[ADD] analytic_partner_hr_timesheet_invoice

### PR DESCRIPTION
**Pull request by pedrobaeza**
# 
# Invoice to the partner specified in analytic lines

This module modifies analytic entries invoicing action for invoicing to
the "Other partner" specified on them. If no other partner is specified, then
the analytic account partner is used.
# Installation

This module is auto-installed by Odoo when _analytic_partner_ and
_hr_timesheet_invoice_ are installed.
# Configuration

You have to set the "Analytic Accounting" permission at user or db level for
seeing the analytic lines.
# Usage

Go to Accounting > Journal entries > Analytic Journal Items, and selecting some
of the lines, click on _More > Create Invoice_. Created invoice(s) will be
split by the other partner field (if any), or the analytic account partner.
# Known issues / Roadmap
- This module fully overwrites invoicing technical method
  (_invoice_cost_create_), so it's incompatible with other modules that also
  change something in the same method. If some hooks are provided on Odoo,
  this module can be changed for respecting inheritance chain.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
cc @antespi @rafaelbn

**Comment by rafaelbn** [comment]
Tested in runbot :+1:

**Comment by janetrp** [comment]
tested :+1:

**Comment by rafaelbn** [comment]
cc @yajo @antespi @sergio-incaser

**Comment by sergio-teruel** [comment]
Tested :+1:

**Comment by pedrobaeza** [comment]
@eLBati, @tafaRU, please merge.

**Pull request merged**
