### PR TITLE
[11.0][ADD] account_move_analytic_recreate

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Temporal module until https://github.com/odoo/odoo/pull/36376 is merged.

@pedrobaeza Do you like the module name or do you prefer another name in mind?

### CODE REVIEW

**Review by NuriaXifre — APPROVED** [review]
Functional review done!

**Comment by AaronHForgeFlow** [comment]
odoo/odoo#36376 was closed, so this is ready for review I think

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: for me the module name is fine.  @pedrobaeza do you agree?

**Pull request merged**
