### PR TITLE
[12.0][MIG]analytic_tag_dimension_purchase_warning

### PR DESCRIPTION
**Pull request by Dangar-Serpentcs**
analytic_tag_dimension_purchase_warning
==================================

### CODE REVIEW

**Comment by sotolucas** [comment]
Hi @pedrobaeza . This one looks ready to merge.

**Comment by pedrobaeza** [comment]
Sorry, I'm not a proper reviewer of this module.

**Comment by kittiu** [comment]
@Dangar-Serpentcs No problem with this module, it tested ok.
Would you add the readme folder? Like this,
https://github.com/Dangar-Serpentcs/account-analytic/tree/12-mig-analytic_tag_dimension_purchase_warning/analytic_tag_dimension/readme

You can also add your self in CONTRIBUTORS.rst too :)

**Comment by kittiu** [comment]
By the way, @Dangar-Serpentcs @sotolucas 
I do have enhanced module to the tag_dimension https://github.com/OCA/account-analytic/pull/251

Would be great if you could look at it.

**Note:**
* So far, I only have problem with @api.onchange(<fields to check>) where I can't make it dynamic to the new object like purchase.order.line that is using it.
* Been using @api.onchange(lambda self: self._analytic_tag_field_name) but not work. So, I have to include all possible analytic tag fields name which make travis Red.

Will appreciate if anyone have the solution.

**Comment by Dangar-Serpentcs** [comment]
> @Dangar-Serpentcs No problem with this module, it tested ok.
> Would you add the readme folder? Like this,
> https://github.com/Dangar-Serpentcs/account-analytic/tree/12-mig-analytic_tag_dimension_purchase_warning/analytic_tag_dimension/readme
> 
> You can also add your self in CONTRIBUTORS.rst too :)

Added

**Review by kittiu — APPROVED** [review]

**Review by ps-tubtim — APPROVED** [review]
Code LGTM. You can use https://github.com/OCA/maintainer-tools to generate README.rst :)

**Pull request merged**
