### PR TITLE
[13.0][MIG] analytic_tag_dimension

### PR DESCRIPTION
**Pull request by Saran440**
Fixed from https://github.com/OCA/account-analytic/pull/307

### CODE REVIEW

**Comment by Saran440** [comment]
@pedrobaeza @carlosdauden @i-vyshnevska Sorry for my mistake. Could you please review again. :)

**Comment by pedrobaeza** [comment]
Some squashing can be done in the middle of the extreme squashing in the other PR, but I'm not going to block this anymore. As it's approved in the other PR, merging

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
@Saran440 please check Travis. Something has not been done the same as the other PR.

**Pull request merged**
